### ISSUE TITLE
[HELP] Probability close to 1

### ISSUE THREAD

**Issue by raffaelemancuso** [daniel258/GEEMediate#2]
I'm trying to use this package. But after an initial:
```
Beginning Cgee S-function, @(#) geeformula.q 4.13 98/01/27
running glm to get initial regression estimate
```
The function fails with the following error message:
```
Error in gee::gee(formula = dupl.formula, id = ID, data = dupl.df, family = family,  : 
  Cgee: error: logistic model for probability has fitted value very close to 1.
estimates diverging; iteration terminated.
```

What am I doing wrong?

**Comment by raffaelemancuso** [comment]
Using `family=gaussian` makes RStudio crash!

**Comment by daniel258** [comment]
Apologies for not noticing this issue earlier! Can you try and and send me a minimal working example?

**Comment by raffaelemancuso** [comment]
> Apologies for not noticing this issue earlier! Can you try and and send me a minimal working example?

I'm very sorry but I switched to another package.

Thanks anyway :)
