### ISSUE TITLE
repeated measures identification parameter not used? 

### ISSUE THREAD

**Issue by eawilson31** [daniel258/GEEMediate#3]
Hello, I'm trying to test for a mediation effect in a repeated measures context. I noticed that the output (GEEfit) does not indicate that my ID variable was used. In fact, looking at the DupliData function, it seems that the ID variable is trivially assigned as if all observations are unique (independent): 

    "df.dupl$ID <- rep(1:n.row,2)"

(this is in line with the GEEfit output, which indicates a max cluster size of 1, when in fact my desired input ID variable has multiple observations per cluster)

Am I understanding correctly that GEEmediate does not allow user defined ID,, or is there something I'm missing in order to run GEEmediate with my own ID variable..? 

Thank you! 

Ethan

**Comment by daniel258** [comment]
Thank you Ethan! The current version of GEEmediate actually only runs IEE - treating different rows of the same cluster as independent. Then the GEE framework is used only within the duplicated data as you pointed out. An analysis "forgetting" about the clusters is still valid, but may have larger standard errors. Does that answer your question?

**Comment by eawilson31** [comment]
Ah ok.  yes after discussing with my stats mentor, I agree that IEE is ok, because gee is using robust SE estimators. I think this is defensible enough for me :) thank you for the quick reply, I super appreciate it!
